# 1. Install dependencies only when needed
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# 2. Builder stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Pass your Atlas URI for the build
ARG MONGO_URI
ENV MONGO_URI=$MONGO_URI
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# 3. Final Production Runner (The tiny image)
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Security: Don't run as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Only copy the minimal files needed to run
COPY --from=builder /app/public ./public
# This copies the standalone folder as the root of our app
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000

# Run the minimal server file generated by Next.js
CMD ["node", "server.js"]